import type { QuestionResponse } from '@/types';

export interface ImportResult {
  questionResponses: QuestionResponse[];
  rankedQualities: string[] | null;
  resumeText: string;
  warnings: string[];
}

export interface ImportError {
  error: string;
}

/**
 * Parse a Career Genie exported .md file back into structured data.
 *
 * @param content - Raw file contents
 * @param predefinedQuestions - Ordered list of canonical question strings used to match and build QuestionResponse[]
 * @returns ImportResult on success, ImportError on fatal validation failure
 */
export function parseExportMarkdown(
  content: string,
  predefinedQuestions: string[],
): ImportResult | ImportError {
  // --- 1. Frontmatter validation ---

  if (!content.startsWith('---')) {
    return { error: 'This file was not generated by Career Genie.' };
  }

  const secondDash = content.indexOf('\n---', 3);
  if (secondDash === -1) {
    return { error: 'This file was not generated by Career Genie.' };
  }

  const frontmatterText = content.slice(3, secondDash).trim();
  const frontmatter: Record<string, string> = {};
  for (const line of frontmatterText.split('\n')) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    const value = line.slice(colonIdx + 1).trim();
    frontmatter[key] = value;
  }

  if (frontmatter['app'] !== 'career-genie') {
    return { error: 'This file was not generated by Career Genie.' };
  }

  if (frontmatter['version'] !== '1') {
    return { error: 'Unsupported file version.' };
  }

  // Body is everything after the closing ---
  const body = content.slice(secondDash + 4); // skip '\n---'

  const warnings: string[] = [];

  // --- 2. Parse reflection questions ---

  // Build defaults from predefined questions
  const questionResponses: QuestionResponse[] = predefinedQuestions.map((q, i) => ({
    questionId: i,
    question: q,
    answer: '',
    whyAnswer: '',
    isComplete: false,
  }));

  const questionsMatch = body.match(/## Reflection Questions([\s\S]*?)(?=\n## |\n*$)/);
  if (!questionsMatch) {
    warnings.push('No Reflection Questions section found in file.');
  } else {
    const questionsSection = questionsMatch[1];
    // Split on ### to get individual question blocks (skip first empty segment)
    const blocks = questionsSection.split(/\n### /).slice(1);

    for (const block of blocks) {
      const lines = block.split('\n');
      const questionText = lines[0].trim();

      // Extract answer: everything between **Answer:** and **Why:** or end of block
      const answerMatch = block.match(/\*\*Answer:\*\* ([\s\S]*?)(?=\n\n\*\*Why:\*\* |\n\n###|\n*$)/);
      const whyMatch = block.match(/\*\*Why:\*\* (.+)/);

      const rawAnswer = answerMatch ? answerMatch[1].trim() : '';
      const rawWhy = whyMatch ? whyMatch[1].trim() : '';

      // Match to predefined questions by exact text
      const predefinedIdx = predefinedQuestions.indexOf(questionText);
      if (predefinedIdx === -1) {
        warnings.push(`Unrecognized question skipped: "${questionText}"`);
        continue;
      }

      questionResponses[predefinedIdx] = {
        questionId: predefinedIdx,
        question: predefinedQuestions[predefinedIdx],
        answer: rawAnswer,
        whyAnswer: rawWhy,
        isComplete: rawAnswer !== '',
      };
    }
  }

  // --- 3. Parse rankings ---

  let rankedQualities: string[] | null = null;

  const rankingsMatch = body.match(/## Priority Rankings[^\n]*\n([\s\S]*?)(?=\n## |\n*$)/);
  if (!rankingsMatch) {
    warnings.push('No Priority Rankings section found in file.');
  } else {
    const rankingLines = rankingsMatch[1]
      .split('\n')
      .map((line) => line.match(/^\d+\.\s+(.+)$/))
      .filter(Boolean)
      .map((m) => m![1].trim());

    rankedQualities = rankingLines.length > 0 ? rankingLines : null;
    if (!rankedQualities) {
      warnings.push('No Priority Rankings section found in file.');
    }
  }

  // --- 4. Parse resume ---

  let resumeText = '';
  const resumeMatch = body.match(/## Resume\n\n([\s\S]*?)(?=\n## |\n*$)/);
  if (resumeMatch) {
    resumeText = resumeMatch[1].trim();
  }

  return { questionResponses, rankedQualities, resumeText, warnings };
}
